#!/usr/bin/env bash
# Idempotent VPS ops for LegendaryMatch: Cloudflare visitor IPs, hashed-asset
# Nginx alias, daily config backup, fail2ban scanner jail (Nginx deny, not
# iptables). Never overwrites /etc/legendarymatch.env. Run as root after
# scripts/vps-release.sh so this tree is on origin/main.
set -euo pipefail

APP=/srv/apps/legendarymatch
SITE=/etc/nginx/sites-available/legendarymatch
CF=/etc/nginx/conf.d/cloudflare-realip.conf
DENY=/etc/nginx/snippets/fail2ban-deny.conf

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root." >&2
  exit 1
fi
if [[ ! -f "${SITE}" ]]; then
  echo "Missing ${SITE}" >&2
  exit 1
fi
if [[ ! -f "${APP}/scripts/vps-backup.sh" ]]; then
  echo "Missing ${APP}/scripts/vps-backup.sh — deploy origin/main first." >&2
  exit 1
fi

chmod +x "${APP}/scripts/vps-backup.sh" "${APP}/scripts/vps-ops-apply.sh" "${APP}/scripts/vps-f2b-deny.sh"

TMP="$(mktemp)"
{
  curl -fsSL https://www.cloudflare.com/ips-v4
  echo
  curl -fsSL https://www.cloudflare.com/ips-v6
  echo
} | awk '
  BEGIN { print "# Generated by vps-ops-apply.sh — restore visitor IPs from Cloudflare" }
  { sub(/\r$/, "") }
  /^[0-9a-fA-F:.\/]+$/ { print "set_real_ip_from " $1 ";" }
  END { print "real_ip_header CF-Connecting-IP;" }
' > "${TMP}"
if [[ "$(grep -c '^set_real_ip_from ' "${TMP}")" -lt 10 ]]; then
  echo "Cloudflare IP list looked too short" >&2
  cat "${TMP}" >&2
  rm -f "${TMP}"
  exit 1
fi
install -m 0644 "${TMP}" "${CF}"
rm -f "${TMP}"

touch "${DENY}"
chmod 0644 "${DENY}"

python3 - "${SITE}" <<'PY'
from pathlib import Path
import shutil
import sys
import time

path = Path(sys.argv[1])
text = path.read_text()
changed = False
if "fail2ban-deny.conf" not in text:
    text = text.replace("server {\n", "server {\n    include snippets/fail2ban-deny.conf;\n")
    changed = True
    print("Included fail2ban-deny snippet")
if "location /_next/static/" not in text:
    needle = "location / {"
    if needle not in text:
        raise SystemExit("Could not find `location / {` in nginx site")
    block = """
    location /_next/static/ {
        alias /srv/apps/legendarymatch/.next/standalone/.next/static/;
        expires 1y;
        access_log off;
    }
"""
    text = text.replace(needle, block + "\n    " + needle)
    changed = True
    print("Inserted /_next/static/ location")
if changed:
    shutil.copy2(path, f"{path}.bak.{int(time.time())}")
    path.write_text(text)
else:
    print("Nginx site already has static alias and deny include")
PY

install -d -m 0755 /etc/fail2ban/filter.d /etc/fail2ban/action.d /etc/fail2ban/jail.d
install -m 0644 "${APP}/scripts/fail2ban/nginx-scanner.filter" /etc/fail2ban/filter.d/nginx-scanner.conf
install -m 0644 "${APP}/scripts/fail2ban/nginx-deny-ip.action" /etc/fail2ban/action.d/nginx-deny-ip.conf
install -m 0644 "${APP}/scripts/fail2ban/nginx-scanner.jail" /etc/fail2ban/jail.d/nginx-scanner.conf

cat > /etc/cron.d/legendarymatch-backup <<'EOF'
SHELL=/bin/bash
PATH=/usr/sbin:/usr/bin:/sbin:/bin
15 3 * * * root /srv/apps/legendarymatch/scripts/vps-backup.sh >/var/log/legendarymatch-backup.log 2>&1
EOF
chmod 0644 /etc/cron.d/legendarymatch-backup

bash "${APP}/scripts/vps-backup.sh"
nginx -t
systemctl reload nginx
systemctl reload fail2ban || systemctl restart fail2ban
fail2ban-client status nginx-scanner
echo "Ops apply complete."
